# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f67b318f611e0473515a4bada90df715af932132d3c21c0670ffab95a83fa0e25295015052c1005b62262761d18fa8a62dd1bd2316e2c61248621b5e7b9bc0f

test:
  secret_key_base: 4e36fff43081a368313bdd2c6afbc828a722cf009d67d34a0c61bc2ed36dacb0a28b2446da004c18fa9006e50d1e30a9f5218ad5f15a893ab937301a0103b1ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
